"""first

Revision ID: 45cef63d2846
Revises: 
Create Date: 2024-07-03 17:16:17.587466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cef63d2846'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Documents_id'), 'Documents', ['id'], unique=False)
    op.create_table('Documents_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_doc', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_doc'], ['Documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Documents_text_id'), 'Documents_text', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Documents_text_id'), table_name='Documents_text')
    op.drop_table('Documents_text')
    op.drop_index(op.f('ix_Documents_id'), table_name='Documents')
    op.drop_table('Documents')
    # ### end Alembic commands ###
