"""second

Revision ID: 53467c648e4b
Revises: 45cef63d2846
Create Date: 2024-07-03 17:30:28.336588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53467c648e4b'
down_revision: Union[str, None] = '45cef63d2846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Documents_text_id_doc_fkey', 'Documents_text', type_='foreignkey')
    op.create_foreign_key(None, 'Documents_text', 'Documents', ['id_doc'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Documents_text', type_='foreignkey')
    op.create_foreign_key('Documents_text_id_doc_fkey', 'Documents_text', 'Documents', ['id_doc'], ['id'])
    # ### end Alembic commands ###
